# version: "3.8"
# services:
#   server:
#     # image: vncharles/instagram-app:1.0
#     build: './InstagramApp'
#     ports:
#       - 8081:8080
#     environment:
#       - spring.datasource.url=jdbc:mysql://mysql-db:3307/instagram-app
#       - spring.datasource.username=root
#       - spring.datasource.password=sapassword
#     depends_on:
#       - mysql-db

#   mysql-db:
#     image: mysql:8.2.0
#     ports:
#       - 3307:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: 'sapassword'
#       MYSQL_DATABASE: instagram-app

version: "3.8"
services:
  server:
    image: vncharles/instagram-app:1.0
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/instagram-app
      - spring.datasource.username=root
      - spring.datasource.password=sapassword
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.2.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'sapassword'
      MYSQL_DATABASE: instagram-app

